version: "3.2"

volumes:
  kafka_data:
    driver: local
  db-data:

networks:
  jenkins:
    driver: bridge

services:
  zookeeper:
      ports:
          - 2181:2181
      image: ubuntu/zookeeper:edge

  kafka:
      container_name: kafka-container
      environment:
          - TZ=UTC
          - ZOOKEEPER_HOST=host.docker.internal
      ports:
          - 9092:9092
      depends_on:
          - zookeeper
      image: ubuntu/kafka:3.1-22.04_beta
      networks:
        - jenkins

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - jenkins

  kproducer:
    image: kafkajava-prod:latest
    build: ./producer
    ports:
      - 5000:8092
    depends_on:
      - db
      - kafka
      - zookeeper
    networks:
      - jenkins

  kconsumer:
    image: kafkajava-prod:latest
    build: ./producer
    ports:
      - 5001:8091
    depends_on:
      - db
      - kafka
      - zookeeper
    networks:
      - jenkins


