version: "1"

volumes:
  kafka_data:
    driver: local
  db-data:

networks:
  jenkins:
    driver: bridge

services:
    kproducer:
      image: kafkajava-prod:latest
      build: ./producer
      ports:
        - 5000:8090
      networks:
        - jenkins

    kconsumer:
      image: kafkajava-prod:latest
      build: ./producer
      ports:
        - 5001:8091
      networks:
        - jenkins

    kafka:
        container_name: kafka-container
        environment:
            - TZ=UTC
            - ZOOKEEPER_HOST=host.docker.internal
        ports:
            - 9092:9092
        image: ubuntu/kafka:3.1-22.04_beta
        networks:
          - jenkins

    zookeeper:
        ports:
            - 2181:2181
        image: ubuntu/zookeeper:edge

    db:
      image: postgres:9.4
      volumes:
        - "db-data:/var/lib/postgresql/data"
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
      networks:
        - jenkins


